//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Ce code source a été automatiquement généré par xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Employes {
    
    private EmployesEmploye[] employeField;
    
    private string versionField;
    
    private string dateExportField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Employe")]
    public EmployesEmploye[] Employe {
        get {
            return this.employeField;
        }
        set {
            this.employeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DateExport {
        get {
            return this.dateExportField;
        }
        set {
            this.dateExportField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class EmployesEmploye {
    
    private string codeField;
    
    private string libelleField;
    
    private string descriptionField;
    
    private string dateInsertionField;
    
    private string dateMajField;
    
    private EmployesEmployeCompte compteField;
    
    private EmployesEmployeCompetence[] competencesField;
    
    private EmployesEmployeConnaissance[] connaissancesField;
    
    private EmployesEmployeEmploi[] emploisField;
    
    private int indiceField;
    
    private bool indiceFieldSpecified;
    
    /// <remarks/>
    public string Code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    public string Libelle {
        get {
            return this.libelleField;
        }
        set {
            this.libelleField = value;
        }
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public string DateInsertion {
        get {
            return this.dateInsertionField;
        }
        set {
            this.dateInsertionField = value;
        }
    }
    
    /// <remarks/>
    public string DateMaj {
        get {
            return this.dateMajField;
        }
        set {
            this.dateMajField = value;
        }
    }
    
    /// <remarks/>
    public EmployesEmployeCompte Compte {
        get {
            return this.compteField;
        }
        set {
            this.compteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Competence", IsNullable=false)]
    public EmployesEmployeCompetence[] Competences {
        get {
            return this.competencesField;
        }
        set {
            this.competencesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Connaissance", IsNullable=false)]
    public EmployesEmployeConnaissance[] Connaissances {
        get {
            return this.connaissancesField;
        }
        set {
            this.connaissancesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Emploi", IsNullable=false)]
    public EmployesEmployeEmploi[] Emplois {
        get {
            return this.emploisField;
        }
        set {
            this.emploisField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int Indice {
        get {
            return this.indiceField;
        }
        set {
            this.indiceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IndiceSpecified {
        get {
            return this.indiceFieldSpecified;
        }
        set {
            this.indiceFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class EmployesEmployeCompte {
    
    private string codeField;
    
    private string mailField;
    
    private string typeCompteField;
    
    private string dateInsertionField;
    
    private string dateMajField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Mail {
        get {
            return this.mailField;
        }
        set {
            this.mailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TypeCompte {
        get {
            return this.typeCompteField;
        }
        set {
            this.typeCompteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DateInsertion {
        get {
            return this.dateInsertionField;
        }
        set {
            this.dateInsertionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DateMaj {
        get {
            return this.dateMajField;
        }
        set {
            this.dateMajField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ConCom {
    
    private string codeField;
    
    private string libelleField;
    
    private string descriptionField;
    
    private string dateInsertionField;
    
    private string dateMajField;
    
    private int indiceField;
    
    private bool indiceFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Libelle {
        get {
            return this.libelleField;
        }
        set {
            this.libelleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DateInsertion {
        get {
            return this.dateInsertionField;
        }
        set {
            this.dateInsertionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DateMaj {
        get {
            return this.dateMajField;
        }
        set {
            this.dateMajField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int Indice {
        get {
            return this.indiceField;
        }
        set {
            this.indiceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IndiceSpecified {
        get {
            return this.indiceFieldSpecified;
        }
        set {
            this.indiceFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class EmployesEmployeCompetence : ConCom {
    
    private int niveauField;
    
    private string dateAcquisitionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int Niveau {
        get {
            return this.niveauField;
        }
        set {
            this.niveauField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DateAcquisition {
        get {
            return this.dateAcquisitionField;
        }
        set {
            this.dateAcquisitionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class EmployesEmployeConnaissance : ConCom {
    
    private int niveauField;
    
    private string dateAcquisitionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int Niveau {
        get {
            return this.niveauField;
        }
        set {
            this.niveauField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DateAcquisition {
        get {
            return this.dateAcquisitionField;
        }
        set {
            this.dateAcquisitionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class EmployesEmployeEmploi : ConCom {
    
    private EmployesEmployeEmploiService serviceField;
    
    private string dateDebutField;
    
    private string dateFinField;
    
    /// <remarks/>
    public EmployesEmployeEmploiService Service {
        get {
            return this.serviceField;
        }
        set {
            this.serviceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DateDebut {
        get {
            return this.dateDebutField;
        }
        set {
            this.dateDebutField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DateFin {
        get {
            return this.dateFinField;
        }
        set {
            this.dateFinField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class EmployesEmployeEmploiService {
    
    private string codeField;
    
    private string libelleField;
    
    /// <remarks/>
    public string Code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    public string Libelle {
        get {
            return this.libelleField;
        }
        set {
            this.libelleField = value;
        }
    }
}
