export * from './apiController.service';
import { ApiControllerService } from './apiController.service';
export * from './compteController.service';
import { CompteControllerService } from './compteController.service';
export * from './connaissanceController.service';
import { ConnaissanceControllerService } from './connaissanceController.service';
export * from './emploiController.service';
import { EmploiControllerService } from './emploiController.service';
export * from './employeController.service';
import { EmployeControllerService } from './employeController.service';
export * from './mailController.service';
import { MailControllerService } from './mailController.service';
export const APIS = [ApiControllerService, CompteControllerService, ConnaissanceControllerService, EmploiControllerService, EmployeControllerService, MailControllerService];
