DROP TABLE "EMPLOYESERVICE";
DROP TABLE "EMPLOYECOMPTENCE";
DROP TABLE "EMPLOYEEMPLOI";
DROP TABLE "EMPLOICOMPETENCE";
DROP TABLE "EMPLOI";
DROP TABLE "SERVICE";
DROP TABLE "COMPTE";
DROP TABLE "COMPETENCE"
DROP TABLE "EMPLOYE";
DROP TABLE "CONNAISSANCE";

/*CREATION DES TABLES PRIMAIRES*/
CREATE TABLE "EMPLOYE" 
(
    "ID"         RAW(16) NOT NULL,
    "CODE"              VARCHAR2(3) NOT NULL,
    "PRENOM"            VARCHAR2(50) NULL,
    "NOM"               VARCHAR2(50) NULL,
    "PRENOMASCII"       VARCHAR2(50) NULL,
    "NOMASCII"          VARCHAR2(50) NULL,
    "PHOTO"             BLOB NULL,
    "TELEPHONE"         NUMBER(10) NULL,
    "MAIL"              VARCHAR2(50) NOT NULL,
    "DATEINSERTION"     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "DATEMAJ"           TIMESTAMP NULL,
    CONSTRAINT PK_EMPLOYE PRIMARY KEY("ID"),
    CONSTRAINT UK_MAIL_EMPLOYE UNIQUE ("MAIL"),
    CONSTRAINT UK_CODE_EMPLOYE UNIQUE ("CODE")
);

CREATE TABLE "COMPETENCE"
(
    "ID"      RAW(16) NOT NULL,
    "CODE"              VARCHAR2(10) NOT NULL,
    "LIBELLE"           VARCHAR2(100) NOT NULL,
    "DESCRIPTION"       VARCHAR2(500) NULL,
    "DATEINSERTION"     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "DATEMAJ"           TIMESTAMP NULL,
    CONSTRAINT PK_COMPETENCE PRIMARY KEY("ID"),
    CONSTRAINT UK_CODE_COMPETENCE UNIQUE ("CODE")
);

CREATE TABLE "EMPLOI"(
    "ID"      RAW(16) NOT NULL,
    "CODE"          VARCHAR2(10) NOT NULL,
    "LIBELLE"       VARCHAR2(100) NOT NULL,
    "DESCRIPTION"   VARCHAR2(500) NULL,
    "DATEINSERTION" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "DATEMAJ"       TIMESTAMP NULL,
    CONSTRAINT PK_EMPLOI PRIMARY KEY ("ID"),
    CONSTRAINT UK_CODE_EMPLOI UNIQUE ("CODE")
);

CREATE TABLE "COMPTE"(
    "ID"                RAW(16) NOT NULL,
    "EMPLOYEID"         RAW(16) NOT NULL,
    "MAIL"              VARCHAR2(50) NOT NULL,
    "PASSWORD"          VARCHAR2(50) NOT NULL,
    "TYPECOMPTE"        VARCHAR2(30) DEFAULT "MEMBRE",
    "DATEINSERTION"     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "DATEMAJ"           TIMESTAMP NULL,
    CONSTRAINT PK_COMPTE) PRIMARY KEY ("ID"),
    CONSTRAINT FK_EMPLOYE_COMPTE FOREIGN KEY ("EMPLOYEID") REFERENCES "EMPLOYE"("ID"),
    CONSTRAINT C1_TYPECOMPTE CHECK (TYPECOMPTE IN ('MEMBRE', 'ADMINISTRATEUR', 'MANAGER'))
);

CREATE TABLE "SERVICE"
(
    "ID"            RAW(16) NOT NULL,
    "CODE"          VARCHAR2(10) NOT NULL,
    "LIBELLE"       VARCHAR2(50) NOT NULL,
    "DATEINSERTION" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "DATEMAJ"       TIMESTAMP NULL,
    CONSTRAINT PK_PERSONNEL PRIMARY KEY ("ID"),
    CONSTRAINT UK_CODE_SERVICE UNIQUE ("CODE")
);

CREATE TABLE "CONNAISSANCE"
(
    "ID"                RAW(16) NOT NULL,
    "CODE"              VARCHAR2(10) NOT NULL,
    "LIBELLE"           VARCHAR2(100) NULL,
    "DESCRIPTION"       VARCHAR2(500) NULL,
    "DATEINSERTION"     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "DATEMAJ"           TIMESTAMP NULL,
    CONSTRAINT PK_CONNAISSANCE PRIMARY KEY ("ID"),
    CONSTRAINT UK_CODE_CONNAISSANCE UNIQUE ("CODE")
);

/*CREATION DES TABLES RELATIONNELLES*/
CREATE TABLE "EMPLOISERVICE"
(
	"ID"			RAW(16) NOT NULL,
    "EMPLOIID"      RAW(16) NOT NULL,
    "SERVICEID"     RAW(16) NOT NULL,
    "DATEDEBUT"     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "DATEFIN"       TIMESTAMP NULL,
	CONSTRAINT PK_EMPLOISERVICE PRIMARY KEY ("ID"),
    CONSTRAINT FK_EMPLOYE_EMPLOYESERVICE FOREIGN KEY ("EMPLOIID") REFERENCES "EMPLOI"("ID"),
    CONSTRAINT FK_SERVICE_EMPLOYESERVICE FOREIGN KEY ("SERVICEID") REFERENCES "SERVICE"("ID")
);

CREATE TABLE "EMPLOYEEMPLOI"
(
	"ID"			RAW(16) NOT NULL,
    "EMPLOYEID"     RAW(16) NOT NULL,
    "EMPLOIID"      RAW(16) NOT NULL,
    "DATEDEBUT"     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "DATEFIN"       TIMESTAMP NULL,
	CONSTRAINT PK_EMPLOYEEMPLOI PRIMARY KEY ("ID"),
    CONSTRAINT FK_EMPLOYE_EMPLOYEEMPLOI FOREIGN KEY ("EMPLOYEID") REFERENCES "EMPLOYE"("ID"),
    CONSTRAINT FK_EMPLOI_EMPLOYEEMPLOI FOREIGN KEY ("EMPLOIID") REFERENCES "EMPLOI"("ID")
);

CREATE TABLE "EMPLOYECOMPETENCE"
(
	"ID"				RAW(16) NOT NULL,
    "COMPETENCEID"      RAW(16) NOT NULL,
    "EMPLOYEID"         RAW(16) NOT NULL,
    "NIVEAU"            NUMBER(1) DEFAULT 0,
    "DATEACQUISITION"   TIMESTAMP NULL,
	CONSTRAINT PK_EMPLOYECOMPETENCE PRIMARY KEY ("ID"),
    CONSTRAINT FK_COMPETENCE_EMPLOYECOMPETENCE FOREIGN KEY ("COMPETENCEID") REFERENCES "COMPETENCE"("ID"),
    CONSTRAINT FK_EMPLOYE_EMPLOYECOMPETENCE FOREIGN KEY ("EMPLOYEID") REFERENCES "EMPLOYE"("ID"),
    CONSTRAINT C3_NIVEAU CHECK (NIVEAU BETWEEN 0 AND 5)
);

CREATE TABLE "EMPLOICOMPETENCE"
(
	"ID" 				RAW(16) NOT NULL,
    "COMPETENCEID"      RAW(16) NOT NULL,
    "EMPLOIID"          RAW(16) NOT NULL,
    "DATEDEBUT"         TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "DATEFIN"           TIMESTAMP NULL,
	CONSTRAINT PK_EMPLOICOMPETENCE FOREIGN KEY ("ID"),
    CONSTRAINT FK_EMPLOI_EMPLOICOMPETENCE FOREIGN KEY ("EMPLOIID") REFERENCES "EMPLOI"("ID"),
    CONSTRAINT FK_COMPETENCE_EMPLOICOMPETENCE FOREIGN KEY ("COMPETENCEID") REFERENCES "COMPETENCE"("ID")
);

CREATE TABLE "EMPLOYECONNAISSANCE"
(
	"ID"				RAW(16) NOT NULL,
    "CONNAISSANCEID"    RAW(16) NOT NULL,
    "EMPLOYEID"         RAW(16) NOT NULL,
    "NIVEAU"            NUMBER(1) DEFAULT 0,
    "DATEACQUISITION"   TIMESTAMP NULL,
	CONSTRAINT PK_EMPLOYECONNAISSANCE PRIMARY KEY REFERENCES ("ID"),
    CONSTRAINT FK_CONNAISSANCE_EMPLOYECONNAISSANCE FOREIGN KEY ("CONNAISSANCEID") REFERENCES "CONNAISSANCE"("ID"),
    CONSTRAINT FK_EMPLOYE_EMPLOYECONNAISSANCE FOREIGN KEY ("EMPLOYEID") REFERENCES "EMPLOYE"("ID"),
    CONSTRAINT C3_NIVEAU CHECK (NIVEAU BETWEEN 0 AND 5)
);

CREATE TABLE "EMPLOICONNAISSANCE"
(
	"ID"				RAW(16) NOT NULL,
    "CONNAISSANCEID"    RAW(16) NOT NULL,
    "EMPLOIID"          RAW(16) NOT NULL,
    "DATEDEBUT"         TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "DATEFIN"           TIMESTAMP NULL,
	CONSTRAINT PK_EMPLOICONNAISSANCE PRIMARY KEY ("ID"),
    CONSTRAINT FK_EMPLOI_EMPLOICONNAISSANCE FOREIGN KEY ("EMPLOIID") REFERENCES "EMPLOI"("ID"),
    CONSTRAINT FK_CONNAISSANCE_EMPLOICONNAISSANCE FOREIGN KEY ("CONNAISSANCEID") REFERENCES "CONNAISSANCE"("ID")
);

/*REQUETE DE CREATION D'INDEX*/
CREATE INDEX Employe_Trigramme ON "EMPLOYE"("CODE");
CREATE INDEX Employe_Emploi_Date ON "EMPLOYEEMPLOI"("DATEDEBUT", "DATEFIN");
CREATE INDEX Employe_Competence_Niveau ON "EMPLOYECOMPETENCE"("NIVEAU");
CREATE INDEX Emploi_Service_Date ON "EMPLOISERVICE"("DATEDEBUT", "DATEFIN");