using SGC.Export.Common;

namespace SGC.Export.Structure
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     Ce code a été généré par un outil.
    //     Version du runtime :4.0.30319.42000
    //
    //     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
    //     le code est régénéré.
    // </auto-generated>
    //------------------------------------------------------------------------------

    using System.Xml.Serialization;

    // 
    // Ce code source a été automatiquement généré par xsd, Version=4.8.3928.0.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Emplois
    {

        private ObjetEmploi[] emploiField;

        private string versionField;

        private System.DateTime dateExportField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Emploi")]
        public ObjetEmploi[] Emploi
        {
            get
            {
                return this.emploiField;
            }
            set
            {
                this.emploiField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime dateExport
        {
            get
            {
                return this.dateExportField;
            }
            set
            {
                this.dateExportField = value;
            }
        }
    }
}
