using SGC.Export.Common;

namespace SGC.Export.Structure
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     Ce code a été généré par un outil.
    //     Version du runtime :4.0.30319.42000
    //
    //     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
    //     le code est régénéré.
    // </auto-generated>
    //------------------------------------------------------------------------------

    using System.Xml.Serialization;

    // 
    // Ce code source a été automatiquement généré par xsd, Version=4.8.3928.0.
    // 

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Employes
    {

        private EmployesEmploye[] employeField;

        private string versionField;

        private System.DateTime dateExportField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Employe")]
        public EmployesEmploye[] Employe
        {
            get
            {
                return this.employeField;
            }
            set
            {
                this.employeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime dateExport
        {
            get
            {
                return this.dateExportField;
            }
            set
            {
                this.dateExportField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class EmployesEmploye
    {

        private string codeField;

        private string libelleField;

        private string descriptionField;

        private System.DateTime dateInsertionField;

        private System.DateTime dateMajField;

        private EmployesEmployeCompteSet compteSetField;

        private ConComCommun[] competencesSetField;

        private ConComCommun[] connaissancesSetField;

        private EmployesEmployeEmploi[] emploisSetField;

        private int indiceField;

        private bool indiceFieldSpecified;

        /// <remarks/>
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        public string libelle
        {
            get
            {
                return this.libelleField;
            }
            set
            {
                this.libelleField = value;
            }
        }

        /// <remarks/>
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public System.DateTime dateInsertion
        {
            get
            {
                return this.dateInsertionField;
            }
            set
            {
                this.dateInsertionField = value;
            }
        }

        /// <remarks/>
        public System.DateTime dateMaj
        {
            get
            {
                return this.dateMajField;
            }
            set
            {
                this.dateMajField = value;
            }
        }

        /// <remarks/>
        public EmployesEmployeCompteSet CompteSet
        {
            get
            {
                return this.compteSetField;
            }
            set
            {
                this.compteSetField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Competence", IsNullable = false)]
        public ConComCommun[] CompetencesSet
        {
            get
            {
                return this.competencesSetField;
            }
            set
            {
                this.competencesSetField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Connaissance", IsNullable = false)]
        public ConComCommun[] ConnaissancesSet
        {
            get
            {
                return this.connaissancesSetField;
            }
            set
            {
                this.connaissancesSetField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Emploi", IsNullable = false)]
        public EmployesEmployeEmploi[] EmploisSet
        {
            get
            {
                return this.emploisSetField;
            }
            set
            {
                this.emploisSetField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int indice
        {
            get
            {
                return this.indiceField;
            }
            set
            {
                this.indiceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool indiceSpecified
        {
            get
            {
                return this.indiceFieldSpecified;
            }
            set
            {
                this.indiceFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class EmployesEmployeCompteSet
    {

        private string codeField;

        private string mailField;

        private string typeCompteField;

        private System.DateTime dateInsertionField;

        private bool dateInsertionFieldSpecified;

        private System.DateTime dateMajField;

        private bool dateMajFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string mail
        {
            get
            {
                return this.mailField;
            }
            set
            {
                this.mailField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string typeCompte
        {
            get
            {
                return this.typeCompteField;
            }
            set
            {
                this.typeCompteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime dateInsertion
        {
            get
            {
                return this.dateInsertionField;
            }
            set
            {
                this.dateInsertionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateInsertionSpecified
        {
            get
            {
                return this.dateInsertionFieldSpecified;
            }
            set
            {
                this.dateInsertionFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime dateMaj
        {
            get
            {
                return this.dateMajField;
            }
            set
            {
                this.dateMajField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateMajSpecified
        {
            get
            {
                return this.dateMajFieldSpecified;
            }
            set
            {
                this.dateMajFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class EmployesEmployeEmploi : ConComBase
    {

        private ServiceBase serviceSetField;

        private System.DateTime dateDebutField;

        private System.DateTime dateFinField;

        /// <remarks/>
        public ServiceBase ServiceSet
        {
            get
            {
                return this.serviceSetField;
            }
            set
            {
                this.serviceSetField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime dateDebut
        {
            get
            {
                return this.dateDebutField;
            }
            set
            {
                this.dateDebutField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime dateFin
        {
            get
            {
                return this.dateFinField;
            }
            set
            {
                this.dateFinField = value;
            }
        }
    }

}
