//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Ce code source a été automatiquement généré par xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Connaissances {
    
    private ConnaissancesConnaissance[] connaissanceField;
    
    private string versionField;
    
    private System.DateTime dateExportField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Connaissance")]
    public ConnaissancesConnaissance[] Connaissance {
        get {
            return this.connaissanceField;
        }
        set {
            this.connaissanceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime DateExport {
        get {
            return this.dateExportField;
        }
        set {
            this.dateExportField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ConnaissancesConnaissance {
    
    private string codeField;
    
    private string libelleField;
    
    private string descriptionField;
    
    private System.DateTime dateInsertionField;
    
    private bool dateInsertionFieldSpecified;
    
    private System.DateTime dateMajField;
    
    private bool dateMajFieldSpecified;
    
    private int indiceField;
    
    private bool indiceFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Libelle {
        get {
            return this.libelleField;
        }
        set {
            this.libelleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime DateInsertion {
        get {
            return this.dateInsertionField;
        }
        set {
            this.dateInsertionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DateInsertionSpecified {
        get {
            return this.dateInsertionFieldSpecified;
        }
        set {
            this.dateInsertionFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime DateMaj {
        get {
            return this.dateMajField;
        }
        set {
            this.dateMajField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DateMajSpecified {
        get {
            return this.dateMajFieldSpecified;
        }
        set {
            this.dateMajFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int Indice {
        get {
            return this.indiceField;
        }
        set {
            this.indiceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IndiceSpecified {
        get {
            return this.indiceFieldSpecified;
        }
        set {
            this.indiceFieldSpecified = value;
        }
    }
}
