/**
 * SGC-Miage V1.0
 * JavaInUse API reference for developers
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Compte { 
    employeId?: string;
    id?: string;
    mail?: string;
    password?: string;
    typeCompte?: Compte.TypeCompteEnum;
}
export namespace Compte {
    export type TypeCompteEnum = 'MEMBRE' | 'ADMINISTRATEUR' | 'MANAGER';
    export const TypeCompteEnum = {
        MEMBRE: 'MEMBRE' as TypeCompteEnum,
        ADMINISTRATEUR: 'ADMINISTRATEUR' as TypeCompteEnum,
        MANAGER: 'MANAGER' as TypeCompteEnum
    };
}
